import { useEffect } from "react";

import Head from "next/head";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import EventContainer from "@/components/EventContainer";
import Footer from "@/components/Footer";

import styles from "@/styles/Home.module.scss";

export default function Home() {

  useEffect(() => {
    function handleScroll() {
      const y = window.scrollY;
      console.log(`y轴滚动距离: ${y}px`);
    }

    console.log("window")
    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>E-port 賦能港</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <Header />
        <Banner />

        <EventContainer title="熱門推薦" />
        <EventContainer
          title="營隊專區"
          link={"/event/camp"}
          linkText="更多營隊"
        />
        <EventContainer
          title="免費專區"
          link={"/event/free"}
          linkText="更多活動"
        />
        <EventContainer
          title="精選活動"
          link={"/event/featured"}
          linkText="更多活動"
        />
        <Footer />
      </main>
    </>
  );
}
