import Head from "next/head";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import VerticalCard from "@/components/VerticalCard";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>E-port 賦能港</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <Header />
        <Banner />
        <div className={styles.home__container}>
          <VerticalCard />
          <VerticalCard />
          <VerticalCard />
          <VerticalCard />
        </div>
      </main>
    </>
  );
}
